In [2]:
# On importe la librairie Pandas, que l'on surnomme 'pd'
import pandas as pd

In [65]:
# 
# chargement du fichier en.openfoodfacts.org.products.csv - Le fichier est placé dans le repertoire courant. 
# certaines colonnes ont été choisies
#
data = pd.read_csv('en.openfoodfacts.org.products.csv', sep='\t', usecols=['code', 
                                                                           'product_name', 
                                                                           'quantity',
                                                                           'packaging', 
                                                                           'brands', 
                                                                           'categories', 
                                                                           'origins', 
                                                                           'labels',
                                                                           'cities',
                                                                           'countries', 
                                                                           'ingredients_text', 
                                                                           'allergens', 
                                                                           'traces', 
                                                                           'serving_size',
                                                                           'ingredients_from_palm_oil_n',
                                                                           'ingredients_that_may_be_from_palm_oil_n',
                                                                           'nutriscore_score',
                                                                           'nutriscore_grade', 
                                                                           'nova_group',
                                                                           'pnns_groups_1',
                                                                           'pnns_groups_2',
                                                                           'main_category',
                                                                           'energy-kcal_100g',
                                                                           'energy_100g',
                                                                           'energy-from-fat_100g',
                                                                           'fat_100g',
                                                                           'saturated-fat_100g',
                                                                           'monounsaturated-fat_100g',
                                                                           'polyunsaturated-fat_100g',
                                                                           'omega-3-fat_100g',
                                                                           'omega-6-fat_100g',                                                                        
                                                                           'trans-fat_100g',
                                                                           'cholesterol_100g',
                                                                           'carbohydrates_100g',
                                                                           'sugars_100g',
                                                                           'starch_100g',
                                                                           'polyols_100g',
                                                                           'fiber_100g',
                                                                           'proteins_100g',                                                                            
                                                                           'salt_100g',
                                                                           'sodium_100g',
                                                                           'alcohol_100g', 
                                                                           'vitamin-a_100g', 
                                                                           'vitamin-d_100g', 
                                                                           'vitamin-e_100g', 
                                                                           'vitamin-k_100g', 
                                                                           'vitamin-c_100g', 
                                                                           'vitamin-b1_100g', 
                                                                           'vitamin-b2_100g', 
                                                                           'vitamin-pp_100g', 
                                                                           'vitamin-b6_100g', 
                                                                           'vitamin-b9_100g', 
                                                                           'folates_100g', 
                                                                           'vitamin-b12_100g', 
                                                                           'biotin_100g',
                                                                           'pantothenic-acid_100g',
                                                                           'bicarbonate_100g',
                                                                           'potassium_100g',
                                                                           'chloride_100g', 
                                                                           'calcium_100g', 
                                                                           'phosphorus_100g',
                                                                           'iron_100g',
                                                                           'magnesium_100g',
                                                                           'zinc_100g', 
                                                                           'copper_100g', 
                                                                           'manganese_100g', 
                                                                           'fluoride_100g', 
                                                                           'selenium_100g', 
                                                                           'chromium_100g', 
                                                                           'molybdenum_100g', 
                                                                           'iodine_100g', 
                                                                           'caffeine_100g', 
                                                                           'taurine_100g', 
                                                                           'ph_100g',
                                                                           'fruits-vegetables-nuts_100g', 
                                                                           'fruits-vegetables-nuts-dried_100g', 
                                                                           'fruits-vegetables-nuts-estimate_100g',
                                                                           'collagen-meat-protein-ratio_100g', 
                                                                           'cocoa_100g',
                                                                           'chlorophyl_100g',
                                                                           'carbon-footprint_100g', 
                                                                           'carbon-footprint-from-meat-or-fish_100g', 
                                                                           'nutrition-score-fr_100g',
                                                                           'glycemic-index_100g',
                                                                           'water-hardness_100g', 
                                                                           'choline_100g',
                                                                           'phylloquinone_100g', 
                                                                           'beta-glucan_100g',
                                                                           'inositol_100g',
                                                                           'carnitine_100g'],
                                                                            dtype = {'code':str,'product_name':str, 'energy-kcal_100g': float}
                                                                           )
# 
# print(data)
#
data.shape

(56108, 90)

In [66]:
# 
# On supprime les blancs dans le champ "code" pour faciliter la recherche des doublons
#
data['code'] = data['code'].str.strip()
data.shape

(56108, 90)

In [67]:
print(data.columns)

Index(['code', 'product_name', 'quantity', 'packaging', 'brands', 'categories',
       'origins', 'labels', 'cities', 'countries', 'ingredients_text',
       'allergens', 'traces', 'serving_size', 'ingredients_from_palm_oil_n',
       'ingredients_that_may_be_from_palm_oil_n', 'nutriscore_score',
       'nutriscore_grade', 'nova_group', 'pnns_groups_1', 'pnns_groups_2',
       'main_category', 'energy-kcal_100g', 'energy_100g',
       'energy-from-fat_100g', 'fat_100g', 'saturated-fat_100g',
       'monounsaturated-fat_100g', 'polyunsaturated-fat_100g',
       'omega-3-fat_100g', 'omega-6-fat_100g', 'trans-fat_100g',
       'cholesterol_100g', 'carbohydrates_100g', 'sugars_100g', 'starch_100g',
       'polyols_100g', 'fiber_100g', 'proteins_100g', 'salt_100g',
       'sodium_100g', 'alcohol_100g', 'vitamin-a_100g', 'vitamin-d_100g',
       'vitamin-e_100g', 'vitamin-k_100g', 'vitamin-c_100g', 'vitamin-b1_100g',
       'vitamin-b2_100g', 'vitamin-pp_100g', 'vitamin-b6_100g',
       'vitamin-b9_100g', 'folates_100g', 'vitamin-b12_100g', 'biotin_100g',
       'pantothenic-acid_100g', 'bicarbonate_100g', 'potassium_100g',
       'chloride_100g', 'calcium_100g', 'phosphorus_100g', 'iron_100g',
       'magnesium_100g', 'zinc_100g', 'copper_100g', 'manganese_100g',
       'fluoride_100g', 'selenium_100g', 'chromium_100g', 'molybdenum_100g',
       'iodine_100g', 'caffeine_100g', 'taurine_100g', 'ph_100g',
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-dried_100g',
       'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'carbon-footprint-from-meat-or-fish_100g',
       'nutrition-score-fr_100g', 'glycemic-index_100g', 'water-hardness_100g',
       'choline_100g', 'phylloquinone_100g', 'beta-glucan_100g',
       'inositol_100g', 'carnitine_100g'],
      dtype='object')

In [70]:
#
# le champ code sert como id de produit et doit être unique. On cherche les possibles doublons.
#
duplicate_Rows_DF = data[data.duplicated(['code'])]
duplicate_rows = duplicate_Rows_DF['code']

In [71]:
#
# Premier doublon le suivant
#

data.loc[data['code'] == '0016000459335']

,code,product_name,quantity,packaging,brands,categories,origins,labels,cities,countries,...,carbon-footprint_100g,carbon-footprint-from-meat-or-fish_100g,nutrition-score-fr_100g,glycemic-index_100g,water-hardness_100g,choline_100g,phylloquinone_100g,beta-glucan_100g,inositol_100g,carnitine_100g
16935,0016000459335,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,États-Unis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16936,0016000459335,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
#
# Deuxième doublon le suivant
#

data.loc[data['code'] == '0019320001376']

,code,product_name,quantity,packaging,brands,categories,origins,labels,cities,countries,...,carbon-footprint_100g,carbon-footprint-from-meat-or-fish_100g,nutrition-score-fr_100g,glycemic-index_100g,water-hardness_100g,choline_100g,phylloquinone_100g,beta-glucan_100g,inositol_100g,carnitine_100g
20308,0019320001376,0.75 oz Nabisco Airplane Cookies - Honey,NaN,NaN,"Kraft Foods Inc.,Nabisco,Monsanto Company",NaN,NaN,NaN,NaN,États-Unis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20309,0019320001376,0.75 oz Nabisco Airplane Cookies - Honey,NaN,NaN,"Kraft Foods Inc.,Nabisco,Monsanto Company",NaN,NaN,NaN,NaN,United States,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
#
# élimination des doublons
#
# sorting par la colonne code  

data.sort_values("code", inplace = True) 

#  
# des doublons on garde le premier dans chaque cas
#
data.drop_duplicates(subset ="code", 
                     keep = "first", inplace = True) 
data.shape

(56106, 90)

In [74]:
#
# Première analyse descriptive pour toutes les colonnes numériques:
#
for col in data.columns:
    if data[col].dtype != 'object':
        print(col,'\n', data[col].describe(),'\n')

cities
 count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: cities, dtype: float64

ingredients_from_palm_oil_n
 count    45787.000000
mean         0.002533
std          0.051557
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          3.000000
Name: ingredients_from_palm_oil_n, dtype: float64

ingredients_that_may_be_from_palm_oil_n
 count    45787.000000
mean         0.039116
std          0.202685
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          4.000000
Name: ingredients_that_may_be_from_palm_oil_n, dtype: float64

nutriscore_score
 count    8719.000000
mean        7.659365
std         9.381726
min       -15.000000
25%         0.000000
50%         7.000000
75%        15.000000
max        36.000000
Name: nutriscore_score, dtype: float64

nova_group
 count    28833.000000
mean         3.735477
std          0.710715
min          1.000000
25%          4.000000
50%          4.000000
75%          4.000000
max          4.000000
Name: nova_group, dtype: float64

energy-kcal_100g
 count    50693.000000
mean      1107.137748
std       1154.012497
min          0.000000
25%        326.000000
50%       1050.000000
75%       1644.000000
max      92048.000000
Name: energy-kcal_100g, dtype: float64

energy_100g
 count    51098.000000
mean      1107.319239
std       1151.930091
min          0.000000
25%        326.000000
50%       1054.000000
75%       1644.000000
max      92048.000000
Name: energy_100g, dtype: float64

energy-from-fat_100g
 count     281.000000
mean      612.509822
std       701.269826
min         0.000000
25%        69.600000
50%       335.000000
75%       984.000000
max      3590.000000
Name: energy-from-fat_100g, dtype: float64

fat_100g
 count    50905.000000
mean        12.522463
std         37.614596
min          0.000000
25%          0.000000
50%          3.920000
75%         19.720000
max       7000.000000
Name: fat_100g, dtype: float64

saturated-fat_100g
 count    44391.000000
mean         4.981065
std         12.806213
min          0.000000
25%          0.000000
50%          1.600000
75%          7.060000
max       2000.000000
Name: saturated-fat_100g, dtype: float64

monounsaturated-fat_100g
 count    6342.000000
mean        9.399200
std        14.926912
min         0.000000
25%         0.312500
50%         3.700000
75%        10.000000
max        78.570000
Name: monounsaturated-fat_100g, dtype: float64

polyunsaturated-fat_100g
 count    6357.000000
mean        6.395340
std        10.547275
min         0.000000
25%         0.000000
50%         2.330000
75%         7.790000
max        71.430000
Name: polyunsaturated-fat_100g, dtype: float64

omega-3-fat_100g
 count    9.000000
mean     1.753333
std      1.402712
min      0.200000
25%      0.400000
50%      1.300000
75%      3.000000
max      3.780000
Name: omega-3-fat_100g, dtype: float64

omega-6-fat_100g
 count    3.000000
mean     1.433333
std      0.929157
min      0.800000
25%      0.900000
50%      1.000000
75%      1.750000
max      2.500000
Name: omega-6-fat_100g, dtype: float64

trans-fat_100g
 count    35678.000000
mean         0.096539
std          2.266303
min         -3.030000
25%          0.000000
50%          0.000000
75%          0.000000
max        369.000000
Name: trans-fat_100g, dtype: float64

cholesterol_100g
 count    35448.000000
mean         0.027336
std          1.595447
min          0.000000
25%          0.000000
50%          0.000000
75%          0.020000
max        300.000000
Name: cholesterol_100g, dtype: float64

carbohydrates_100g
 count    50936.000000
mean        32.007859
std         34.685659
min          0.000000
25%          6.400000
50%         20.000000
75%         58.600000
max       2100.000000
Name: carbohydrates_100g, dtype: float64

sugars_100g
 count    47906.000000
mean        15.316618
std         21.095932
min         -1.200000
25%          1.300000
50%          5.560000
75%         21.880000
max        600.000000
Name: sugars_100g, dtype: float64

starch_100g
 count    23.000000
mean     14.573913
std      19.422883
min       0.400000
25%       0.500000
50%       2.400000
75%      25.250000
max      70.300000
Name: starch_100g, dtype: float64

polyols_100g
 count      5.000000
mean      35.940000
std       40.547725
min        1.000000
25%        2.000000
50%       31.700000
75%       45.000000
max      100.000000
Name: polyols_100g, dtype: float64

fiber_100g
 count    36650.000000
mean         2.754355
std          5.474563
min         -6.700000
25%          0.000000
50%          1.500000
75%          3.600000
max        375.000000
Name: fiber_100g, dtype: float64

proteins_100g
 count    50863.000000
mean         6.925662
std          9.843785
min         -3.570000
25%          0.000000
50%          4.080000
75%         10.000000
max        700.000000
Name: proteins_100g, dtype: float64

salt_100g
 count    50446.000000
mean         4.653189
std         92.020796
min          0.000000
25%          0.060960
50%          0.619880
75%          1.450340
max      14300.000000
Name: salt_100g, dtype: float64

sodium_100g
 count    50439.000000
mean         1.861587
std         36.810309
min          0.000000
25%          0.024384
50%          0.248000
75%          0.580136
max       5720.000000
Name: sodium_100g, dtype: float64

alcohol_100g
 count    239.000000
mean       1.263598
std        4.122063
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max       43.000000
Name: alcohol_100g, dtype: float64

vitamin-a_100g
 count    33772.000000
mean         0.000264
std          0.021774
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000107
max          4.000000
Name: vitamin-a_100g, dtype: float64

vitamin-d_100g
 count    1941.000000
mean        0.000007
std         0.000129
min         0.000000
25%         0.000001
50%         0.000001
75%         0.000003
max         0.005000
Name: vitamin-d_100g, dtype: float64

vitamin-e_100g
 count    41.000000
mean      0.008534
std       0.009734
min       0.000000
25%       0.002000
50%       0.005000
75%       0.012900
max       0.050000
Name: vitamin-e_100g, dtype: float64

vitamin-k_100g
 count    120.000000
mean       0.000149
std        0.000247
min        0.000000
25%        0.000006
50%        0.000017
75%        0.000160
max        0.000828
Name: vitamin-k_100g, dtype: float64

vitamin-c_100g
 count    34308.000000
mean         0.010415
std          0.299030
min         -0.002100
25%          0.000000
50%          0.000000
75%          0.003000
max         35.714300
Name: vitamin-c_100g, dtype: float64

vitamin-b1_100g
 count    2975.000000
mean        1.286651
std        17.949623
min         0.000000
25%         0.006000
50%         0.038000
75%         0.489000
max       910.000000
Name: vitamin-b1_100g, dtype: float64

vitamin-b2_100g
 count    2875.000000
mean        0.303176
std         1.971563
min         0.000000
25%         0.003269
50%         0.014783
75%         0.303571
max        42.500000
Name: vitamin-b2_100g, dtype: float64

vitamin-pp_100g
 count    3097.000000
mean        0.016425
std         0.386012
min         0.000000
25%         0.003200
50%         0.005333
75%         0.007143
max        21.428571
Name: vitamin-pp_100g, dtype: float64

vitamin-b6_100g
 count    1444.000000
mean        0.335698
std         4.624410
min         0.000000
25%         0.000212
50%         0.000714
75%         0.001562
max        89.300000
Name: vitamin-b6_100g, dtype: float64

vitamin-b9_100g
 count    1114.000000
mean        0.000075
std         0.000132
min         0.000000
25%         0.000033
50%         0.000055
75%         0.000059
max         0.001960
Name: vitamin-b9_100g, dtype: float64

folates_100g
 count    843.000000
mean       0.250919
std        5.893244
min        0.000000
25%        0.000029
50%        0.000114
75%        0.000214
max      166.666667
Name: folates_100g, dtype: float64

vitamin-b12_100g
 count    9.420000e+02
mean     8.006611e-06
std      3.806642e-05
min      0.000000e+00
25%      9.600000e-07
50%      2.540000e-06
75%      5.170000e-06
max      8.600000e-04
Name: vitamin-b12_100g, dtype: float64

biotin_100g
 count    5.000000
mean     0.000093
std      0.000099
min      0.000013
25%      0.000021
50%      0.000030
75%      0.000194
max      0.000207
Name: biotin_100g, dtype: float64

pantothenic-acid_100g
 count    374.000000
mean       0.052377
std        0.862428
min        0.000000
25%        0.000353
50%        0.000476
75%        0.001429
max       16.670000
Name: pantothenic-acid_100g, dtype: float64

bicarbonate_100g
 count     2.000000
mean     46.300000
std      65.478088
min       0.000000
25%      23.150000
50%      46.300000
75%      69.450000
max      92.600000
Name: bicarbonate_100g, dtype: float64

potassium_100g
 count    6642.000000
mean        0.316555
std         1.191418
min         0.000000
25%         0.104000
50%         0.171000
75%         0.321000
max        66.667000
Name: potassium_100g, dtype: float64

chloride_100g
 count    1.000
mean     0.313
std        NaN
min      0.313
25%      0.313
50%      0.313
75%      0.313
max      0.313
Name: chloride_100g, dtype: float64

calcium_100g
 count    33984.000000
mean         0.131229
std          4.609253
min          0.000000
25%          0.000000
50%          0.031000
75%          0.100000
max        667.000000
Name: calcium_100g, dtype: float64

phosphorus_100g
 count    1302.000000
mean        0.249054
std         0.216023
min         0.000000
25%         0.088000
50%         0.200000
75%         0.357000
max         2.143000
Name: phosphorus_100g, dtype: float64

iron_100g
 count    34440.000000
mean         0.003558
std          0.148120
min          0.000000
25%          0.000000
50%          0.000870
75%          0.002250
max         19.200000
Name: iron_100g, dtype: float64

magnesium_100g
 count    1213.000000
mean        0.757439
std        14.453477
min         0.000000
25%         0.019000
50%         0.060000
75%         0.133000
max       364.286000
Name: magnesium_100g, dtype: float64

zinc_100g
 count    938.000000
mean       0.005652
std        0.006716
min        0.000000
25%        0.001070
50%        0.003210
75%        0.010000
max        0.051720
Name: zinc_100g, dtype: float64

copper_100g
 count    518.000000
mean       0.000680
std        0.000586
min        0.000000
25%        0.000186
50%        0.000571
75%        0.001071
max        0.002414
Name: copper_100g, dtype: float64

manganese_100g
 count    348.000000
mean       0.001238
std        0.001062
min        0.000000
25%        0.000000
50%        0.001000
75%        0.002000
max        0.005000
Name: manganese_100g, dtype: float64

fluoride_100g
 count    1.000
mean     0.025
std        NaN
min      0.025
25%      0.025
50%      0.025
75%      0.025
max      0.025
Name: fluoride_100g, dtype: float64

selenium_100g
 count    135.000000
mean       0.000028
std        0.000036
min       -0.000002
25%        0.000005
50%        0.000010
75%        0.000032
max        0.000150
Name: selenium_100g, dtype: float64

chromium_100g
 count    2.000000
mean     0.000080
std      0.000004
min      0.000077
25%      0.000079
50%      0.000080
75%      0.000081
max      0.000083
Name: chromium_100g, dtype: float64

molybdenum_100g
 count    2.000000
mean     0.000086
std      0.000049
min      0.000052
25%      0.000069
50%      0.000086
75%      0.000104
max      0.000121
Name: molybdenum_100g, dtype: float64

iodine_100g
 count    7.000000
mean     0.001242
std      0.001986
min      0.000031
25%      0.000059
50%      0.000103
75%      0.002075
max      0.004290
Name: iodine_100g, dtype: float64

caffeine_100g
 count    5.000000
mean     0.027684
std      0.018939
min      0.009720
25%      0.018700
50%      0.018700
75%      0.033300
max      0.058000
Name: caffeine_100g, dtype: float64

taurine_100g
 count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: taurine_100g, dtype: float64

ph_100g
 count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: ph_100g, dtype: float64

fruits-vegetables-nuts_100g
 count     18.000000
mean      35.577778
std       29.559264
min        0.000000
25%       17.500000
50%       28.500000
75%       47.000000
max      100.000000
Name: fruits-vegetables-nuts_100g, dtype: float64

fruits-vegetables-nuts-dried_100g
 count    1.0
mean     0.0
std      NaN
min      0.0
25%      0.0
50%      0.0
75%      0.0
max      0.0
Name: fruits-vegetables-nuts-dried_100g, dtype: float64

fruits-vegetables-nuts-estimate_100g
 count     49.000000
mean      44.918367
std       31.917541
min        7.000000
25%       17.000000
50%       40.000000
75%       63.200000
max      100.000000
Name: fruits-vegetables-nuts-estimate_100g, dtype: float64

collagen-meat-protein-ratio_100g
 count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: collagen-meat-protein-ratio_100g, dtype: float64

cocoa_100g
 count    39.000000
mean     58.167179
std      24.595967
min       3.000000
25%      36.500000
50%      68.000000
75%      76.500000
max      99.000000
Name: cocoa_100g, dtype: float64

chlorophyl_100g
 count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: chlorophyl_100g, dtype: float64

carbon-footprint_100g
 count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: carbon-footprint_100g, dtype: float64

carbon-footprint-from-meat-or-fish_100g
 count      37.000000
mean      590.922973
std       673.557380
min        14.800000
25%       135.240000
50%       485.100000
75%       710.400000
max      3580.000000
Name: carbon-footprint-from-meat-or-fish_100g, dtype: float64

nutrition-score-fr_100g
 count    8719.000000
mean        7.659365
std         9.381726
min       -15.000000
25%         0.000000
50%         7.000000
75%        15.000000
max        36.000000
Name: nutrition-score-fr_100g, dtype: float64

glycemic-index_100g
 count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: glycemic-index_100g, dtype: float64

water-hardness_100g
 count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: water-hardness_100g, dtype: float64

choline_100g
 count    1.0000
mean     0.0736
std         NaN
min      0.0736
25%      0.0736
50%      0.0736
75%      0.0736
max      0.0736
Name: choline_100g, dtype: float64

phylloquinone_100g
 count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: phylloquinone_100g, dtype: float64

beta-glucan_100g
 count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: beta-glucan_100g, dtype: float64

inositol_100g
 count    1.0000
mean     0.0276
std         NaN
min      0.0276
25%      0.0276
50%      0.0276
75%      0.0276
max      0.0276
Name: inositol_100g, dtype: float64

carnitine_100g
 count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: carnitine_100g, dtype: float64

In [76]:
# description des données - colonne trans-fat_100g avec des vableurs négatives

print(data.loc[data['trans-fat_100g']<0,:])

                code                            product_name quantity  \
31168  0028190008477  Xtra Butter Microwave Pop Corn, Butter      NaN

      packaging      brands categories origins labels  cities      countries  \
31168       NaN  Jolly Time        NaN     NaN    NaN     NaN  United States

       ... carbon-footprint_100g carbon-footprint-from-meat-or-fish_100g  \
31168  ...                   NaN                                     NaN

      nutrition-score-fr_100g glycemic-index_100g  water-hardness_100g  \
31168                     NaN                 NaN                  NaN

       choline_100g  phylloquinone_100g beta-glucan_100g  inositol_100g  \
31168           NaN                 NaN              NaN            NaN

      carnitine_100g
31168            NaN

[1 rows x 90 columns]

In [77]:
# description des données - colonne sugars_100g avec des vableurs négatives

print(data.loc[data['sugars_100g']<0,:])

                code                               product_name quantity  \
10888  0011213420608              Grade A Fancy Chopped Spinach      NaN
23971  0021130493432  Select, Spicy Red Bell Pepper Pasta Sauce      NaN

      packaging     brands categories origins labels  cities      countries  \
10888       NaN    Spartan        NaN     NaN    NaN     NaN  United States
23971       NaN  Signature        NaN     NaN    NaN     NaN  United States

       ... carbon-footprint_100g carbon-footprint-from-meat-or-fish_100g  \
10888  ...                   NaN                                     NaN
23971  ...                   NaN                                     NaN

      nutrition-score-fr_100g glycemic-index_100g  water-hardness_100g  \
10888                     NaN                 NaN                  NaN
23971                     NaN                 NaN                  NaN

       choline_100g  phylloquinone_100g beta-glucan_100g  inositol_100g  \
10888           NaN                 NaN              NaN            NaN
23971           NaN                 NaN              NaN            NaN

      carnitine_100g
10888            NaN
23971            NaN

[2 rows x 90 columns]

In [78]:
# description des données - colonne proteins_100g avec des vableurs négatives 

print(data.loc[data['proteins_100g']<0,:])

                code   product_name quantity packaging     brands categories  \
44250  0036800416727  Whole Cashews      NaN       NaN  Food Club        NaN

      origins labels  cities      countries  ... carbon-footprint_100g  \
44250     NaN    NaN     NaN  United States  ...                   NaN

      carbon-footprint-from-meat-or-fish_100g nutrition-score-fr_100g  \
44250                                     NaN                     NaN

      glycemic-index_100g  water-hardness_100g  choline_100g  \
44250                 NaN                  NaN           NaN

       phylloquinone_100g beta-glucan_100g  inositol_100g carnitine_100g
44250                 NaN              NaN            NaN            NaN

[1 rows x 90 columns]

In [79]:
# description des données - colonne selenium_100g avec des vableurs négatives 

print(data.loc[data['selenium_100g']<0,:])

                code             product_name quantity packaging  \
37556  0032971251990  Venus, Cuttlefish Balls      NaN       NaN

                  brands categories origins labels  cities      countries  \
37556  Venus Foods  Inc.        NaN     NaN    NaN     NaN  United States

       ... carbon-footprint_100g carbon-footprint-from-meat-or-fish_100g  \
37556  ...                   NaN                                     NaN

      nutrition-score-fr_100g glycemic-index_100g  water-hardness_100g  \
37556                     NaN                 NaN                  NaN

       choline_100g  phylloquinone_100g beta-glucan_100g  inositol_100g  \
37556           NaN                 NaN              NaN            NaN

      carnitine_100g
37556            NaN

[1 rows x 90 columns]

In [82]:
#
# les 9 colonnes suivantes seront eliminées du dataframe car elles sont nulles pour tous les registres
#
null_columns = ['ph_100g', 'collagen-meat-protein-ratio_100g', 'chlorophyl_100g', 'carbon-footprint_100g',
               'glycemic-index_100g', 'water-hardness_100g', 'phylloquinone_100g',
                'beta-glucan_100g', 'carnitine_100g']
for null_column in null_columns:
    data.drop(null_column, axis=1, inplace=True)
data.shape

KeyError: "['ph_100g'] not found in axis"

In [81]:
#
# description des données - colonnes code avec des valeurs manquantes
#
Index_label = data[pd.isnull(data['code'])].index.tolist()
print('Il y a ',len(Index_label), ' lignes avec product_name manquant')

Il y a  0  lignes avec product_name manquant

In [56]:
#
# lire dans un dataframe les noms possibles de la France en plusieurs langues - fichier france_names_latin_alphabets.csv
#
france_names = pd.read_csv('france_names_latin_alphabets.csv',header=None)
#
# on met tous en minuscule
#
france_names[0] = france_names[0].apply(lambda x: x.lower())
#
# on enkève les blancs au début età la fin
#
france_names[0] = france_names[0].apply(lambda x: x.strip())
france_names

                      0
0              frankryk
1                franca
2                frança
3               francie
4              frankrig
5             frankrijk
6                france
7           prantsusmaa
8                ranska
9               francia
10           frankreich
11        franciaország
12            frakkland
13             perancis
14           an fhrainc
15              francia
16             francija
17           prancūzija
18            frankrike
19              francja
20               franța
21           francúzsko
22             ufaransa
23            frankrike
24             pransiya
25               fransa
26                 pháp
27              ffrainc
28                   fr
29  polynésie française
30           guadeloupe
31           martinique
32           la réunion

In [83]:
#
# Convertir tous les pays de la colonne "countries" du dataframe en minuscule
#

data["countries"] = data["countries"].map(lambda x: x if type(x)!=str else x.lower())

In [84]:
list_of_countries = data.groupby(['countries']).count()
print(list_of_countries)

                            code  product_name  quantity  packaging  brands  \
countries
alemania, spain                1             1         0          0       1
alemania,luxemburgo,españa     1             1         0          0       1
algérie                        1             1         0          0       0
allemagne                      3             3         2          1       2
allemagne, en:france           1             1         1          1       1
...                          ...           ...       ...        ...     ...
法国, 香港                         1             1         1          0       1
法国,香港                          1             1         1          1       1
澳大利亚, 法国, 新西兰                  1             1         1          1       1
美国                             1             1         0          0       1
香港                             1             1         1          1       1

                            categories  origins  labels  cities  \
countries
alemania, spain                      1        0       0       0
alemania,luxemburgo,españa           1        0       1       0
algérie                              0        0       0       0
allemagne                            2        0       0       0
allemagne, en:france                 1        0       0       0
...                                ...      ...     ...     ...
法国, 香港                               1        0       0       0
法国,香港                                1        0       0       0
澳大利亚, 法国, 新西兰                        1        0       0       0
美国                                   0        0       1       0
香港                                   1        0       0       0

                            ingredients_text  ...  caffeine_100g  \
countries                                     ...
alemania, spain                            0  ...              0
alemania,luxemburgo,españa                 0  ...              0
algérie                                    1  ...              0
allemagne                                  1  ...              0
allemagne, en:france                       1  ...              0
...                                      ...  ...            ...
法国, 香港                                     0  ...              0
法国,香港                                      1  ...              0
澳大利亚, 法国, 新西兰                              1  ...              0
美国                                         0  ...              0
香港                                         1  ...              0

                            taurine_100g  fruits-vegetables-nuts_100g  \
countries
alemania, spain                        0                            0
alemania,luxemburgo,españa             0                            0
algérie                                0                            0
allemagne                              0                            0
allemagne, en:france                   0                            0
...                                  ...                          ...
法国, 香港                                 0                            0
法国,香港                                  0                            0
澳大利亚, 法国, 新西兰                          0                            0
美国                                     0                            0
香港                                     0                            0

                            fruits-vegetables-nuts-dried_100g  \
countries
alemania, spain                                             0
alemania,luxemburgo,españa                                  0
algérie                                                     0
allemagne                                                   0
allemagne, en:france                                        0
...                                                       ...
法国, 香港                                                      0
法国,香港                                                       0
澳大利亚, 法国, 新西兰                                               0
美国                                                          0
香港                                                          0

                            fruits-vegetables-nuts-estimate_100g  cocoa_100g  \
countries
alemania, spain                                                0           0
alemania,luxemburgo,españa                                     0           0
algérie                                                        0           0
allemagne                                                      0           0
allemagne, en:france                                           0           0
...                                                          ...         ...
法国, 香港                                                         0           0
法国,香港                                                          0           0
澳大利亚, 法国, 新西兰                                                  0           0
美国                                                             0           0
香港                                                             0           0

                            carbon-footprint-from-meat-or-fish_100g  \
countries
alemania, spain                                                   0
alemania,luxemburgo,españa                                        0
algérie                                                           0
allemagne                                                         0
allemagne, en:france                                              0
...                                                             ...
法国, 香港                                                            0
法国,香港                                                             0
澳大利亚, 法国, 新西兰                                                     0
美国                                                                0
香港                                                                0

                            nutrition-score-fr_100g  choline_100g  \
countries
alemania, spain                                   1             0
alemania,luxemburgo,españa                        0             0
algérie                                           0             0
allemagne                                         2             0
allemagne, en:france                              1             0
...                                             ...           ...
法国, 香港                                            0             0
法国,香港                                             1             0
澳大利亚, 法国, 新西兰                                     1             0
美国                                                0             0
香港                                                0             0

                            inositol_100g
countries
alemania, spain                         0
alemania,luxemburgo,españa              0
algérie                                 0
allemagne                               0
allemagne, en:france                    0
...                                   ...
法国, 香港                                  0
法国,香港                                   0
澳大利亚, 法国, 新西兰                           0
美国                                      0
香港                                      0

[566 rows x 80 columns]

In [85]:
#
# On eliimine du dataframe les produits que n'ont pas la France dans leur colonne "countries"
#
# D'abord, on passe tous les noms de France vers une liste pour que ce soit facil de faire des itérations
#
valid_codes_france = france_names[0].tolist()
#
# print(valid_codes_france)
#
# On choisit les lignes du dataframe qui ont la France dans leur liste de "countries"
#
# data 3 stocke tous les produits dont la colonne "countries" contient la France
#
pattern = '|'.join(valid_codes_france)
data = data.loc[(data['countries'].str.contains(pattern, case=False, na=False))]

In [86]:
#print(data)
data.shape

(6540, 81)

In [87]:
#
# exporte cette premiére ensemble nettoyé vers le fichier csv fr.openfoodfacts.products.csv
# le fichier se trouvera dans le repertoire courant
#
data.to_csv (r'fr.openfoodfacts.products.csv', index = False, header=True)

In [88]:
list_of_countries = data.groupby(['countries']).count()
print(list_of_countries)

                                          code  product_name  quantity  \
countries
allemagne, en:france                         1             1         1
aruba,france                                 1             1         0
australia, en:france                         1             1         1
australia, france                            6             6         3
australia, france, sweden, united states     1             1         1
...                                        ...           ...       ...
united states, en:france                     1             1         0
états-unis, en:fr                            2             2         0
états-unis, en:france                       37            36        11
états-unis,en:france                         1             0         0
états-unis,polynésie française               1             1         0

                                          packaging  brands  categories  \
countries
allemagne, en:france                              1       1           1
aruba,france                                      0       1           1
australia, en:france                              0       1           1
australia, france                                 2       5           4
australia, france, sweden, united states          1       1           1
...                                             ...     ...         ...
united states, en:france                          0       1           0
états-unis, en:fr                                 0       2           0
états-unis, en:france                             9      36          16
états-unis,en:france                              0       1           1
états-unis,polynésie française                    0       1           1

                                          origins  labels  cities  \
countries
allemagne, en:france                            0       0       0
aruba,france                                    0       0       0
australia, en:france                            0       0       0
australia, france                               3       3       0
australia, france, sweden, united states        0       0       0
...                                           ...     ...     ...
united states, en:france                        0       0       0
états-unis, en:fr                               0       0       0
états-unis, en:france                           1       8       0
états-unis,en:france                            0       0       0
états-unis,polynésie française                  0       0       0

                                          ingredients_text  ...  \
countries                                                   ...
allemagne, en:france                                     1  ...
aruba,france                                             1  ...
australia, en:france                                     1  ...
australia, france                                        2  ...
australia, france, sweden, united states                 1  ...
...                                                    ...  ...
united states, en:france                                 1  ...
états-unis, en:fr                                        2  ...
états-unis, en:france                                   31  ...
états-unis,en:france                                     1  ...
états-unis,polynésie française                           1  ...

                                          caffeine_100g  taurine_100g  \
countries
allemagne, en:france                                  0             0
aruba,france                                          0             0
australia, en:france                                  0             0
australia, france                                     0             0
australia, france, sweden, united states              0             0
...                                                 ...           ...
united states, en:france                              0             0
états-unis, en:fr                                     0             0
états-unis, en:france                                 0             0
états-unis,en:france                                  0             0
états-unis,polynésie française                        0             0

                                          fruits-vegetables-nuts_100g  \
countries
allemagne, en:france                                                0
aruba,france                                                        0
australia, en:france                                                0
australia, france                                                   0
australia, france, sweden, united states                            0
...                                                               ...
united states, en:france                                            0
états-unis, en:fr                                                   0
états-unis, en:france                                               0
états-unis,en:france                                                0
états-unis,polynésie française                                      0

                                          fruits-vegetables-nuts-dried_100g  \
countries
allemagne, en:france                                                      0
aruba,france                                                              0
australia, en:france                                                      0
australia, france                                                         0
australia, france, sweden, united states                                  0
...                                                                     ...
united states, en:france                                                  0
états-unis, en:fr                                                         0
états-unis, en:france                                                     0
états-unis,en:france                                                      0
états-unis,polynésie française                                            0

                                          fruits-vegetables-nuts-estimate_100g  \
countries
allemagne, en:france                                                         0
aruba,france                                                                 0
australia, en:france                                                         0
australia, france                                                            1
australia, france, sweden, united states                                     0
...                                                                        ...
united states, en:france                                                     0
états-unis, en:fr                                                            0
états-unis, en:france                                                        0
états-unis,en:france                                                         0
états-unis,polynésie française                                               0

                                          cocoa_100g  \
countries
allemagne, en:france                               0
aruba,france                                       0
australia, en:france                               1
australia, france                                  0
australia, france, sweden, united states           0
...                                              ...
united states, en:france                           0
états-unis, en:fr                                  0
états-unis, en:france                              0
états-unis,en:france                               0
états-unis,polynésie française                     0

                                          carbon-footprint-from-meat-or-fish_100g  \
countries
allemagne, en:france                                                            0
aruba,france                                                                    0
australia, en:france                                                            0
australia, france                                                               0
australia, france, sweden, united states                                        0
...                                                                           ...
united states, en:france                                                        0
états-unis, en:fr                                                               0
états-unis, en:france                                                           0
états-unis,en:france                                                            0
états-unis,polynésie française                                                  0

                                          nutrition-score-fr_100g  \
countries
allemagne, en:france                                            1
aruba,france                                                    1
australia, en:france                                            0
australia, france                                               4
australia, france, sweden, united states                        1
...                                                           ...
united states, en:france                                        0
états-unis, en:fr                                               0
états-unis, en:france                                          16
états-unis,en:france                                            0
états-unis,polynésie française                                  0

                                          choline_100g  inositol_100g
countries
allemagne, en:france                                 0              0
aruba,france                                         0              0
australia, en:france                                 0              0
australia, france                                    0              0
australia, france, sweden, united states             0              0
...                                                ...            ...
united states, en:france                             0              0
états-unis, en:fr                                    0              0
états-unis, en:france                                0              0
états-unis,en:france                                 0              0
états-unis,polynésie française                       0              0

[214 rows x 80 columns]

In [89]:
print(data.columns)

Index(['code', 'product_name', 'quantity', 'packaging', 'brands', 'categories',
       'origins', 'labels', 'cities', 'countries', 'ingredients_text',
       'allergens', 'traces', 'serving_size', 'ingredients_from_palm_oil_n',
       'ingredients_that_may_be_from_palm_oil_n', 'nutriscore_score',
       'nutriscore_grade', 'nova_group', 'pnns_groups_1', 'pnns_groups_2',
       'main_category', 'energy-kcal_100g', 'energy_100g',
       'energy-from-fat_100g', 'fat_100g', 'saturated-fat_100g',
       'monounsaturated-fat_100g', 'polyunsaturated-fat_100g',
       'omega-3-fat_100g', 'omega-6-fat_100g', 'trans-fat_100g',
       'cholesterol_100g', 'carbohydrates_100g', 'sugars_100g', 'starch_100g',
       'polyols_100g', 'fiber_100g', 'proteins_100g', 'salt_100g',
       'sodium_100g', 'alcohol_100g', 'vitamin-a_100g', 'vitamin-d_100g',
       'vitamin-e_100g', 'vitamin-k_100g', 'vitamin-c_100g', 'vitamin-b1_100g',
       'vitamin-b2_100g', 'vitamin-pp_100g', 'vitamin-b6_100g',
       'vitamin-b9_100g', 'folates_100g', 'vitamin-b12_100g', 'biotin_100g',
       'pantothenic-acid_100g', 'bicarbonate_100g', 'potassium_100g',
       'chloride_100g', 'calcium_100g', 'phosphorus_100g', 'iron_100g',
       'magnesium_100g', 'zinc_100g', 'copper_100g', 'manganese_100g',
       'fluoride_100g', 'selenium_100g', 'chromium_100g', 'molybdenum_100g',
       'iodine_100g', 'caffeine_100g', 'taurine_100g',
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-dried_100g',
       'fruits-vegetables-nuts-estimate_100g', 'cocoa_100g',
       'carbon-footprint-from-meat-or-fish_100g', 'nutrition-score-fr_100g',
       'choline_100g', 'inositol_100g'],
      dtype='object')